sudo: false
language: ruby
cache: bundler
bundler_args: "--without development production"
env:
  - SLOW_SPECS=true SKILLSHARE_SECRET_TOKEN=22d4eeff3dd0cdb77751cfd9b98dd442e7fd5ea9fad41c0331a89670df18589ffa96699300f9412fb2c456161903a6edc5b567c420ff6a573782e42a28375ac8
before_script: bundle exec rake db:create
before_install:
  - gem install bundler
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: QL+A1RiDfquAOtpavIfOl7sfj5S5U4rcr8B2lvEIEZKCpH60DAXCRmhGGDZa4ZYSSW4kuB5kgKBhs+CMomVvenl/PnYAG5IR7a76/YhiwrNV+bVKZ2BXyUgGOC717DDNWMQzAY3V7yGMG28gcoMm+2dORhpEJMtW2tOuC8LaOmE=
  app: ea-skillshare-staging
  on:
    repo: patbl/Skillshare.im
