sudo: false
language: ruby
bundler_args: "--without development production"
rvm:
  - 2.4.1
env:
  - SLOW_SPECS=true SKILLSHARE_SECRET_TOKEN=22d4eeff3dd0cdb77751cfd9b98dd442e7fd5ea9fad41c0331a89670df18589ffa96699300f9412fb2c456161903a6edc5b567c420ff6a573782e42a28375ac8
before_install:
  - gem install bundler -v '= 1.7.0'
before_script: rake db:create
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: gk62FYTX4ef9XUOZ0SX34KdqAJi9MaNhToAC/jicLInInlC1WepRQRTcfUhtRCFgVQ3HVRiV0wBCaw2N4DG0o1Hn1qwg9319TgqXxzpsxvoqTyGK1UKx8HR3DJVynywfQXbbdg0W+HkmdzACW+EXbpRGbim5hHj5Ynpx7XEs870=
  app: ea-skillshare-staging
  on:
    repo: patbl/Skillshare.im
