sudo: false
language: ruby
cache: bundler
bundler_args: "--without development production"
rvm:
  - 2.4.1
env:
  - SLOW_SPECS=true SKILLSHARE_SECRET_TOKEN=22d4eeff3dd0cdb77751cfd9b98dd442e7fd5ea9fad41c0331a89670df18589ffa96699300f9412fb2c456161903a6edc5b567c420ff6a573782e42a28375ac8
before_script: rake db:create
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: ep/c69wPToiK+TDvAhtQwLqpYv7tHGBI0t3jmmw90LMRXqkkJAS3gljpOX3jesYqTrxYbe+EhW3P5ohAUDzlAlj9J8Sj0CHrk74RWaNa4XVmz0hESNmMGYRXa+Q/gOliL7TZJTdVYVogpNkInt9GwGeUmn9Mlz4d96B5H54BSIU=
  app: ea-skillshare-staging
  on:
    repo: patbl/Skillshare.im
