sudo: false
language: ruby
cache: bundler
bundler_args: "--without development production"
services:
- postgresql
before_script: bundle exec rake db:create
before_install:
- gem install bundler
script:
- RAILS_ENV=test bin/rails db:migrate --trace
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: YhYa1XbJmSW4f7ELgPgkLb4bpHdYnOuMyxvTB51HaiBmfOJ4J4XhDsRS5L0/095PVB4rJogivGOq9qwvPJUKwsbIC960tFZry0xzL39lb0raP0PD0FyKEVZAo1PmjPEmB+1kICVL7RqsDFN8gJPJsiIP7SqHKSG6kEl60GuesOc=
  app: ea-skillshare-staging
  on:
    repo: patbl/Skillshare.im
