development:
  adapter: postgresql
  encoding: unicode
  database: skillshare_development
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch("POSTGRES_USERNAME", "postgres") %>
  password:
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

test:
  adapter: postgresql
  encoding: unicode
  database: skillshare_test
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch("POSTGRES_USERNAME", "postgres") %>
  password:
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
